In [1]:
import sys
sys.path.append(".")

from game_class import tictactoe

import numpy as np
import pandas as pd
import pathlib
import os
import glob
from time import sleep,time
from datetime import datetime
from IPython.core import display as ICD

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.utils import plot_model

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", 100)

In [2]:
def load_model(name):
    return keras.models.load_model('Models/'+name)

model=load_model('model_2')

In [ ]:
ttt=tictactoe(model=model)
ttt.play()

...Reset data...
Enter mode (c ---> vs computer, h ---> vs human ) : c
...Reset data...
--------------------------------------------------
[0 0 0 0 0 0 0 0 0]
----------------
|  1 | 2  | 3  |
----------------
| 4  | 5  | 6  |
----------------
| 7  | 8  | 9  |
----------------

----------------
|    |    |    |
----------------
|    |    |    |
----------------
|    |    |    |
----------------

Enter cell index to place X : 3


2022-01-25 11:15:33.234306: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


--------------------------------------------------
[0 0 1 0 0 0 0 0 0]
----------------
|  1 | 2  | 3  |
----------------
| 4  | 5  | 6  |
----------------
| 7  | 8  | 9  |
----------------

----------------
|    |    | X  |
----------------
|    |    |    |
----------------
|    |    |    |
----------------

--------------------------------------------------
[-1  0  1  0  0  0  0  0  0]
----------------
|  1 | 2  | 3  |
----------------
| 4  | 5  | 6  |
----------------
| 7  | 8  | 9  |
----------------

----------------
|  O |    | X  |
----------------
|    |    |    |
----------------
|    |    |    |
----------------

Enter cell index to place X : 5
--------------------------------------------------
[-1  0  1  0  1  0  0  0  0]
----------------
|  1 | 2  | 3  |
----------------
| 4  | 5  | 6  |
----------------
| 7  | 8  | 9  |
----------------

----------------
|  O |    | X  |
----------------
|    | X  |    |
----------------
|    |    |    |
----------------

-----------------

Enter cell index to place X : 2
--------------------------------------------------
[ 1  1 -1 -1 -1  1  1 -1  1]
----------------
|  1 | 2  | 3  |
----------------
| 4  | 5  | 6  |
----------------
| 7  | 8  | 9  |
----------------

----------------
|  X | X  | O  |
----------------
| O  | O  | X  |
----------------
| X  | O  | X  |
----------------

Draw...
New game? (y/n): y
--------------------------------------------------
NEW GAME : 
----------------
|  1 | 2  | 3  |
----------------
| 4  | 5  | 6  |
----------------
| 7  | 8  | 9  |
----------------

----------------
|    |    |    |
----------------
|    |    |    |
----------------
|    |    |    |
----------------

Enter cell index to place X : 3
--------------------------------------------------
[0 0 1 0 0 0 0 0 0]
----------------
|  1 | 2  | 3  |
----------------
| 4  | 5  | 6  |
----------------
| 7  | 8  | 9  |
----------------

----------------
|    |    | X  |
----------------
|    |    |    |
----------------
|    |    