In [1]:
import sys
sys.path.append(".")

from game_class import tictactoe

import numpy as np
import pandas as pd
import pathlib
import os
import glob
from time import sleep,time
from datetime import datetime
from IPython.core import display as ICD

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.utils import plot_model

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", 100)

In [2]:
def load_model(name):
    return keras.models.load_model('Models/'+name)

model=load_model('model_2')

2021-11-29 19:06:06.804863: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-29 19:06:06.805799: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.


In [3]:
ttt=tictactoe(model=model)
ttt.play()

...Reset data...
Enter mode (c ---> vs computer, h ---> vs human ) : c
...Reset data...
--------------------------------------------------
[0 0 0 0 0 0 0 0 0]
----------------
|  1 | 2  | 3  |
----------------
| 4  | 5  | 6  |
----------------
| 7  | 8  | 9  |
----------------

----------------
|    |    |    |
----------------
|    |    |    |
----------------
|    |    |    |
----------------

Enter cell index to place X : 4
--------------------------------------------------
[0 0 0 1 0 0 0 0 0]
----------------
|  1 | 2  | 3  |
----------------
| 4  | 5  | 6  |
----------------
| 7  | 8  | 9  |
----------------

----------------
|    |    |    |
----------------
| X  |    |    |
----------------
|    |    |    |
----------------

--------------------------------------------------
[ 0 -1  0  1  0  0  0  0  0]
----------------
|  1 | 2  | 3  |
----------------
| 4  | 5  | 6  |
----------------
| 7  | 8  | 9  |
----------------

----------------
|    | O  |    |
----------------
| X  | 